package Users;

import Services.DeviceRepair;
import Services.Service;
import Services.Status;

import java.util.ArrayList;
import java.util.Objects;
import java.util.Stack;

public class ServiceProvider extends User {
    private String skillType;
    private int jobsCount = 0;
    private ArrayList<Service> services = new ArrayList<>();

    public ServiceProvider(int id, String name, String phoneNo, String email, String skillType){
        super(id, name, phoneNo, email);
        this.skillType = skillType;
    }
    public void assignService(Service service){
        if(!service.getIsAssigned()){
            return;
        }
        for (Service value : services) {
            if (Objects.equals(value.getType(), service.getType())) {
                System.out.println("Service provider is not available");
                return;
            }
        }
        services.add(service);
    }
    public int getJobsCount(){
        for (Service service : services) {
            if (!Objects.equals(service.getStatus(), Status.COMPLETED) && !Objects.equals(service.getStatus(), Status.valueOf("CANCELLED"))) {
                jobsCount++;
            }
        }
        return jobsCount;
    }
    public void getServicesBySkill(String skill){
        if(services.isEmpty()){
            System.out.println("Services does not exist");
            return;
        }
        for(Service service: services){
            System.out.println("Type of Service: " + service.getType());
            System.out.println("Request generated by: " + service.getCustomer().getName());
            System.out.println("Request Status: " + service.getStatus());
            System.out.println("Request created on: " + service.getDate());
            System.out.println("Request Base Cost: " + service.getBaseCost());
        }
    }
    public String getSkillType(){
        return skillType;
    }
}
